---
- hosts: all
  remote_user: root

  vars_files:
   - ../../vars/vars.yml
    
    
  tasks:
 
   - debug: msg="CephAdmNode {{CephAdmNode}} CephMonNode {% for host in CephMonNode %}{{ host }}{%- if not loop.last -%},{% endif %}{% endfor %} CephAllNode {% for host in CephAllNode %}{{ host }}{%- if not loop.last -%},{% endif %}{% endfor %} CephOsdNode {% for host in CephOsdNode %}{{ host }}{%- if not loop.last -%},{% endif %}{% endfor %}"         
          
   - name: add ceph release key
     apt_key:
      url: "https://download.ceph.com/keys/release.asc"
      state: present
     
   - name: add ceph repo 
     apt_repository:
      repo: deb https://download.ceph.com/debian-{{ceph_stable_release}} xenial main 
      state: present
      filename: 'ceph'
      
   - name: Update repositories cache and install "ceph-deploy" package
     apt:
      name: ceph-deploy
      update_cache: yes 
          
   - name: Crea directorios
     become_user: "{{ cephuser }}" 
     file:
      path: /home/{{cephuser}}/cluster
      state: directory      

   
   - name: ceph-deploy --cluster {{ cluster_name }} new {% for host in CephMonNode %}{{ host }}{%- if not loop.last -%} {% endif %}{% endfor %}
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     register: deploy
     shell: ceph-deploy --cluster {{ cluster_name }} new {% for host in CephMonNode %}{{ host }}{%- if not loop.last -%} {% endif %}{% endfor %}
     args:
      chdir: /home/{{cephuser}}/cluster


   - name: Cambia OSD poll size a 2
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     lineinfile:
      dest: /home/{{cephuser}}/cluster/ceph.conf
      state: present
      regexp: '^osd pool default size'
      line: 'osd pool default size = 2'

   - name: Agrega public network
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     lineinfile:
      dest: /home/{{cephuser}}/cluster/ceph.conf
      state: present
      regexp: '^public network'
      line: 'public network = {{ public_network }}/{{ public_network_netmask }}'
   
   - name: Ejecuta ceph deploy install {% for host in groups.all[0:] -%}{{ hostvars[host].inventory_hostname }} {% endfor %}}
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     register: deploy
     shell: ceph-deploy install {% for host in groups.all[0:] -%}{{ hostvars[host].inventory_hostname }} {% endfor %}}
     args:
      chdir: /home/{{cephuser}}/cluster
     when: not dev
     
   - name: Ejecuta ceph mon create-initial
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     shell: ceph-deploy mon create-initial
     args:
      chdir: /home/{{cephuser}}/cluster
     when: not dev


