---
- hosts: all
  remote_user: vagrant

  vars_files:
   - ../../vars/vars.yml
    
    
  tasks:

   - name: Crea directorios
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}" 
     file:
      path: /home/{{cephuser}}/cluster
      state: directory      

   
   - name: ceph deploy node 1 
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     shell: ceph-deploy new {{nodebase}}-1 
     args:
      chdir: /home/{{cephuser}}/cluster


   - name: Cambia OSD poll size a 2
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     lineinfile:
      dest: /home/{{cephuser}}/cluster/ceph.conf
      state: present
      regexp: '^osd pool default size'
      line: 'osd pool default size = 2'

   - name: Agrega public network
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     lineinfile:
      dest: /home/{{cephuser}}/cluster/ceph.conf
      state: present
      regexp: '^public network'
      line: 'public network = {{public_network}}.0/255.255.255.0'

   - name: Agrega cluster network
     become: yes
     become_method: "sudo"
     become_user: "{{ cephuser }}"
     lineinfile:
      dest: /home/{{cephuser}}/cluster/ceph.conf
      state: present
      regexp: '^cluster network'
      line: 'cluster network = {{cluster_network}}.0/255.255.255.0'



#ceph-deploy install admin-node node1 node2 node3
