---
- hosts: all
  remote_user: vagrant

  vars_files:
   - ../../vars/vars.yml
    
    
  tasks:

   - name: Allow {{ cephuser }} to have passwordless sudo
     lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ cephuser }}'
      line: '{{ cephuser }} ALL=(ALL) NOPASSWD: ALL'
      
   - name: crea grupo {{ cephuser }}
     group: name={{ cephuser }} state=present
  
   - name: crea usuario {{ cephuser }}
     user: name={{ cephuser }} group={{ cephuser }} groups=adm shell=/bin/bash state=present password={{password}}

   - name: crea dir .ssh
     file:
      path: /home/{{ cephuser }}/.ssh
      owner: "{{ cephuser }}"
      group: "{{ cephuser }}"
      mode: 0700      
      state: directory

   - name: copia id_rsa.pub {{ cephuser }}
     copy:
      src: ../templates/ssh/id_rsa.pub
      dest: /home/{{ cephuser }}/.ssh/id_rsa.pub
      owner: "{{ cephuser }}"
      group: "{{ cephuser }}"
      mode: 0600

   - name: copia id_rsa {{ cephuser }}
     copy:
      src: ../templates/ssh/id_rsa
      dest: /home/{{ cephuser }}/.ssh/id_rsa
      owner: "{{ cephuser }}"
      group: "{{ cephuser }}"
      mode: 0600

   - name: copia config ssh
     template:
      src: ../templates/ssh/config
      dest: /home/{{ cephuser }}/.ssh/config
      owner: "{{ cephuser }}"
      group: "{{ cephuser }}"
      mode: 0600

   - name: Set authorized key took from file
     authorized_key:
      user: "{{ cephuser }}"
      state: present
      key: "{{ lookup('file', '../templates/ssh/id_rsa.pub') }}"
      
   - name: crea filesystem en vdb XFS
     filesystem:
      fstype: xfs
      dev: /dev/vdb
