---
- hosts: all
  remote_user: vagrant

  vars_files:
   - ../../vars/vars.yml
    
    
  tasks:

   - debug: msg="Running setenv playbook"  
      
   #- name: updates a server
     #when: not dev 
     #apt: update_cache=yes
   
   #- name: upgrade a server
     #when: not dev 
     #apt: upgrade=dist
   
   #- name: instala paquetes
     #when: not dev 
     #apt: name="{{ item }}" state=present
     #with_items:
      #- ntp     
      
   - name: Allow vagrant to have passwordless sudo
     when: not dev
     lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^vagrant'
      line: 'vagrant ALL=(ALL) NOPASSWD: ALL'

      
   - name: Allow {{ cephuser }} to have passwordless sudo
     when: not dev
     lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ cephuser }}'
      line: '{{ cephuser }} ALL=(ALL) NOPASSWD: ALL'

      
   - name: crea grupo {{ cephgroup }}
     when: not dev
     group: name={{ cephgroup }} state=present

  
   - name: crea usuario {{ cephuser }}
     when: not dev
     user: name={{ cephuser }} group={{ cephgroup }} groups=adm shell=/bin/bash state=present password={{password}} createhome=yes home=/var/lib/{{ cephuser }}

   - name: crea dir .ssh
     when: not dev
     file:
      path: //var/lib/{{ cephuser }}/.ssh
      owner: "{{ cephuser }}"
      group: "{{ cephgroup }}"
      mode: 0700      
      state: directory

   - name: copia id_rsa.pub {{ cephuser }}
     when: not dev
     copy:
      src: ../templates/ssh/id_rsa.pub
      dest: /var/lib/{{ cephuser }}/.ssh/id_rsa.pub
      owner: "{{ cephuser }}"
      group: "{{ cephgroup }}"
      mode: 0600

   - name: copia id_rsa {{ cephuser }}
     when: not dev
     copy:
      src: ../templates/ssh/id_rsa
      dest: /var/lib/{{ cephuser }}/.ssh/id_rsa
      owner: "{{ cephuser }}"
      group: "{{ cephgroup }}"
      mode: 0600

   - name: copia config ssh
     when: not dev
     template:
      src: ../templates/ssh/config
      dest: /var/lib/{{ cephuser }}/.ssh/config
      owner: "{{ cephuser }}"
      group: "{{ cephgroup }}"
      mode: 0600

   - name: Set authorized key took from file
     when: not dev
     authorized_key:
      user: "{{ cephuser }}"
      state: present
      key: "{{ lookup('file', '../templates/ssh/id_rsa.pub') }}" 
